version: '3.7'

services:
  ipwhitelister:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETOS=linux
        - TARGETARCH=arm64
    command: ["/app/ipwhitelister"]
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
